import { calculateAreaPerformance, calculateOverallAccuracy, calculateProgress } from './analytics.js';
import { buildStudyPriorities } from './study-engine.js';

const DATA_PATHS = { exams:'./data/provas.json', questions:'./data/questoes.json', errors:'./data/erros.json', reviews:'./data/revisoes.json' };
const AREA_ORDER = ['Clínica Médica','Cirurgia','Ginecologia e Obstetrícia','Pediatria','Medicina Preventiva'];
const STATUS_LABELS = { in_progress:'Em andamento', completed:'Concluída', planned:'Planejada' };
const $ = (s) => document.querySelector(s);
const text = (s,v) => { const el=$(s); if(el) el.textContent=v; };
const html = (s,v) => { const el=$(s); if(el) el.innerHTML=v; };
function localDateISO(date=new Date()){const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,10)}
function formatDate(date,options={}){return new Intl.DateTimeFormat('pt-BR',options).format(date)}
function greetingForHour(hour){if(hour<12)return'Bom dia, Joyce.';if(hour<18)return'Boa tarde, Joyce.';return'Boa noite, Joyce.'}
async function loadJSON(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`Falha ao carregar ${path}`);return r.json()}
async function loadAllData(){const entries=await Promise.all(Object.entries(DATA_PATHS).map(async([k,p])=>[k,await loadJSON(p)]));return Object.fromEntries(entries)}
function renderShared(){const now=new Date();text('#today-date',formatDate(now,{day:'2-digit',month:'short'}).replace('.','').toUpperCase());text('#greeting',greetingForHour(now.getHours()));}
function activeExam(exams){return exams.find((e)=>e.status==='in_progress')??exams[0]}
function renderHome(data){const exam=activeExam(data.exams);const registered=data.questions.filter((q)=>q.correct===true||q.correct===false).length;text('#questions-registered',String(registered));if(!exam){text('#focus-title','Nenhuma prova em andamento');text('#focus-status','Livre');return}const p=calculateProgress(exam);text('#focus-title',exam.name);text('#focus-status',STATUS_LABELS[exam.status]??'Em andamento');text('#focus-progress-count',`${p.answered} / ${p.total} questões`);text('#focus-progress-percent',`${p.percentage}%`);const bar=$('#focus-progress-bar');if(bar)bar.style.width=`${p.percentage}%`;const track=$('.progress-track');if(track)track.setAttribute('aria-valuenow',String(p.percentage));text('#hero-subtitle',`Continue de onde parou. ${Math.max(0,p.total-p.answered)} questões ainda não foram registradas como concluídas.`)}
function renderExams(exams){const root=$('#exam-list');if(!root)return;if(!exams.length){root.innerHTML='<div class="empty-state">Nenhuma prova cadastrada.</div>';return}root.innerHTML=exams.map((exam)=>{const p=calculateProgress(exam);const accuracy=exam.correctAnswers==null||!exam.answeredQuestions?null:Math.round((exam.correctAnswers/exam.answeredQuestions)*1000)/10;return `<article class="exam-card"><div class="exam-top"><div><h2>${exam.name}</h2><div class="exam-meta"><span>${STATUS_LABELS[exam.status]??exam.status}</span><span>${p.answered}/${p.total} respondidas</span>${exam.startedAt?`<span>início ${new Date(`${exam.startedAt}T12:00:00`).toLocaleDateString('pt-BR')}</span>`:''}</div></div><span class="status">${p.percentage}%</span></div><div class="progress-track"><span class="progress-fill" style="width:${p.percentage}%"></span></div><p class="subtle" style="margin:12px 0 0">${accuracy==null?'O desempenho aparece quando houver respostas individuais registradas.':`${accuracy}% de acerto`}</p></article>`}).join('')}
function renderPerformance(questions){const root=$('#area-performance');if(!root)return;const overall=calculateOverallAccuracy(questions);text('#overall-accuracy',overall==null?'—':`${overall}%`);text('#accuracy-caption',overall==null?'Ainda não há questões corrigidas suficientes para calcular sua taxa.':`${questions.filter((q)=>q.correct===true||q.correct===false).length} questões com resultado registrado.`);const byArea=new Map(calculateAreaPerformance(questions).map((a)=>[a.area,a]));root.innerHTML=AREA_ORDER.map((area)=>{const d=byArea.get(area);return `<article class="area-card"><div class="area-head"><strong>${area}</strong><span class="area-value">${d?`${d.accuracy}%`:'—'}</span></div><div class="area-track"><div class="area-fill" style="width:${d?d.accuracy:0}%"></div></div><p class="area-note">${d?`${d.answered} questões registradas`:'Aguardando questões corrigidas nesta grande área.'}</p></article>`}).join('')}
function renderErrors(errors){const root=$('#error-list');if(!root)return;if(!errors.length){root.innerHTML='<div class="empty-state">Nenhum erro consolidado ainda. Conforme você enviar as questões corrigidas, padrões recorrentes aparecem aqui sem poluir o dashboard.</div>';return}root.innerHTML=[...errors].sort((a,b)=>(b.occurrences||1)-(a.occurrences||1)).map((e)=>`<article class="list-card"><div class="list-card-top"><div><h2>${e.topic}</h2><div class="list-meta"><span>${e.area||'Área não informada'}</span><span>${e.occurrences||1} ocorrência(s)</span></div></div><span class="status">Revisar</span></div></article>`).join('')}
function renderReviews(reviews,priorities){const today=localDateISO();const due=reviews.filter((r)=>r.status!=='done'&&r.dueDate===today);text('#reviews-today',String(due.length));text('#reviews-today-detail',due.length?`${due.reduce((s,r)=>s+(Number(r.questionCount)||0),0)} questões previstas`:'nenhuma revisão cadastrada');const root=$('#priority-list');if(!root)return;if(!priorities.length){root.innerHTML='<div class="empty-state">Sem revisões ou erros prioritários cadastrados ainda.</div>';return}root.innerHTML=priorities.map((p)=>`<article class="list-card"><div class="list-card-top"><div><h2>${p.title}</h2><p class="subtle" style="margin:6px 0 0">${p.detail}</p></div><span class="status">${p.type==='error'?'Erro':'Revisão'}</span></div></article>`).join('')}
function startOfWeek(date){const d=new Date(date);const day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));d.setHours(12,0,0,0);return d}
function renderWeek(reviews,exams){const root=$('#week-strip');if(!root)return;const today=new Date();const todayISO=localDateISO(today);const monday=startOfWeek(today);const exam=activeExam(exams);root.innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const iso=localDateISO(d);const dayReviews=reviews.filter((r)=>r.status!=='done'&&r.dueDate===iso);const tasks=[];if(iso===todayISO&&exam){const remaining=Math.max(0,(Number(exam.totalQuestions)||0)-(Number(exam.answeredQuestions)||0));tasks.push(`<li class="week-task"><strong>${exam.name}</strong><br>${remaining} questões restantes</li>`)}dayReviews.forEach((r)=>tasks.push(`<li class="week-task"><strong>${r.topic}</strong><br>${r.questionCount||0} questões de revisão</li>`));if(!tasks.length)tasks.push('<li class="week-task">Sem tarefa registrada</li>');return `<article class="week-day ${iso===todayISO?'is-today':''}"><div class="week-day-head"><span class="week-day-name">${formatDate(d,{weekday:'short'}).replace('.','')}</span><span class="week-day-date">${formatDate(d,{day:'2-digit'})}</span></div><ul class="week-tasks">${tasks.join('')}</ul></article>`}).join('')}
async function init(){renderShared();try{const data=await loadAllData();const priorities=buildStudyPriorities({errors:data.errors,reviews:data.reviews,today:localDateISO()});renderHome(data);renderExams(data.exams);renderPerformance(data.questions);renderErrors(data.errors);renderReviews(data.reviews,priorities);renderWeek(data.reviews,data.exams)}catch(error){console.error(error);const targets=['#exam-list','#area-performance','#error-list','#priority-list','#week-strip'];targets.forEach((s)=>{if($(s))html(s,'<div class="empty-state">Não foi possível carregar os dados agora.</div>')})}}
document.addEventListener('DOMContentLoaded',init);
